/**********************************************************************
 * Copyright (C) 2025 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

import type { Endpoints } from '@octokit/types';

export const mockRepositoryData: Endpoints['GET /repos/{owner}/{repo}']['response']['data'] = {
  id: 465844859,
  node_id: 'R_kgDOG8Q6ew',
  name: 'podman-desktop',
  full_name: 'podman-desktop/podman-desktop',
  private: false,
  owner: {
    login: 'podman-desktop',
    id: 129859460,
    node_id: 'O_kgDOB71_hA',
    avatar_url: 'https://avatars.githubusercontent.com/u/129859460?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/podman-desktop',
    html_url: 'https://github.com/podman-desktop',
    followers_url: 'https://api.github.com/users/podman-desktop/followers',
    following_url: 'https://api.github.com/users/podman-desktop/following{/other_user}',
    gists_url: 'https://api.github.com/users/podman-desktop/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/podman-desktop/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/podman-desktop/subscriptions',
    organizations_url: 'https://api.github.com/users/podman-desktop/orgs',
    repos_url: 'https://api.github.com/users/podman-desktop/repos',
    events_url: 'https://api.github.com/users/podman-desktop/events{/privacy}',
    received_events_url: 'https://api.github.com/users/podman-desktop/received_events',
    type: 'Organization',
    user_view_type: 'public',
    site_admin: false,
  },
  html_url: 'https://github.com/podman-desktop/podman-desktop',
  description:
    'Podman Desktop is the best free and open source tool to work with Containers and Kubernetes for developers. Get an intuitive and user-friendly interface to effortlessly build, manage, and deploy containers and Kubernetes — all from your desktop.',
  fork: false,
  url: 'https://api.github.com/repos/podman-desktop/podman-desktop',
  forks_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/forks',
  keys_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/keys{/key_id}',
  collaborators_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/collaborators{/collaborator}',
  teams_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/teams',
  hooks_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/hooks',
  issue_events_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/issues/events{/number}',
  events_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/events',
  assignees_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/assignees{/user}',
  branches_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/branches{/branch}',
  tags_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/tags',
  blobs_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/git/blobs{/sha}',
  git_tags_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/git/tags{/sha}',
  git_refs_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/git/refs{/sha}',
  trees_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/git/trees{/sha}',
  statuses_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/statuses/{sha}',
  languages_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/languages',
  stargazers_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/stargazers',
  contributors_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/contributors',
  subscribers_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/subscribers',
  subscription_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/subscription',
  commits_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/commits{/sha}',
  git_commits_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/git/commits{/sha}',
  comments_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/comments{/number}',
  issue_comment_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/issues/comments{/number}',
  contents_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/contents/{+path}',
  compare_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/compare/{base}...{head}',
  merges_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/merges',
  archive_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/{archive_format}{/ref}',
  downloads_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/downloads',
  issues_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/issues{/number}',
  pulls_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/pulls{/number}',
  milestones_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/milestones{/number}',
  notifications_url:
    'https://api.github.com/repos/podman-desktop/podman-desktop/notifications{?since,all,participating}',
  labels_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/labels{/name}',
  releases_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases{/id}',
  deployments_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/deployments',
  created_at: '2022-03-03T18:45:51Z',
  updated_at: '2025-07-24T06:49:38Z',
  pushed_at: '2025-07-24T07:04:01Z',
  git_url: 'git://github.com/podman-desktop/podman-desktop.git',
  ssh_url: 'git@github.com:podman-desktop/podman-desktop.git',
  clone_url: 'https://github.com/podman-desktop/podman-desktop.git',
  svn_url: 'https://github.com/podman-desktop/podman-desktop',
  homepage: 'https://podman-desktop.io',
  size: 1470011,
  stargazers_count: 6140,
  watchers_count: 6140,
  language: 'TypeScript',
  has_issues: true,
  has_projects: true,
  has_downloads: true,
  has_wiki: true,
  has_pages: true,
  has_discussions: true,
  forks_count: 413,
  mirror_url: null,
  archived: false,
  disabled: false,
  open_issues_count: 586,
  license: {
    key: 'apache-2.0',
    name: 'Apache License 2.0',
    spdx_id: 'Apache-2.0',
    url: 'https://api.github.com/licenses/apache-2.0',
    node_id: 'MDc6TGljZW5zZTI=',
  },
  allow_forking: true,
  is_template: false,
  web_commit_signoff_required: true,
  topics: [
    'container',
    'containers',
    'desktop',
    'docker',
    'hacktoberfest',
    'kubernetes',
    'podman',
    'podman-desktop',
    'tray-application',
    'ui',
  ],
  visibility: 'public',
  forks: 413,
  open_issues: 586,
  watchers: 6140,
  default_branch: 'main',
  temp_clone_token: null,
  custom_properties: {},
  organization: {
    login: 'podman-desktop',
    id: 129859460,
    node_id: 'O_kgDOB71_hA',
    avatar_url: 'https://avatars.githubusercontent.com/u/129859460?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/podman-desktop',
    html_url: 'https://github.com/podman-desktop',
    followers_url: 'https://api.github.com/users/podman-desktop/followers',
    following_url: 'https://api.github.com/users/podman-desktop/following{/other_user}',
    gists_url: 'https://api.github.com/users/podman-desktop/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/podman-desktop/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/podman-desktop/subscriptions',
    organizations_url: 'https://api.github.com/users/podman-desktop/orgs',
    repos_url: 'https://api.github.com/users/podman-desktop/repos',
    events_url: 'https://api.github.com/users/podman-desktop/events{/privacy}',
    received_events_url: 'https://api.github.com/users/podman-desktop/received_events',
    type: 'Organization',
    user_view_type: 'public',
    site_admin: false,
  },
  network_count: 413,
  subscribers_count: 50,
};
