/**********************************************************************
 * Copyright (C) 2025 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

import type { Endpoints } from '@octokit/types';

export const mockReleaseData: Endpoints['GET /repos/{owner}/{repo}/releases/latest']['response']['data'] = {
  url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/224602012',
  assets_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/224602012/assets',
  upload_url: 'https://uploads.github.com/repos/podman-desktop/podman-desktop/releases/224602012/assets{?name,label}',
  html_url: 'https://github.com/podman-desktop/podman-desktop/releases/tag/v1.19.2',
  id: 224602012,
  author: {
    login: 'github-actions[bot]',
    id: 41898282,
    node_id: 'MDM6Qm90NDE4OTgyODI=',
    avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/github-actions%5Bbot%5D',
    html_url: 'https://github.com/apps/github-actions',
    followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
    following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
    gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
    organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
    repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
    events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
    received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
    type: 'Bot',
    user_view_type: 'public',
    site_admin: false,
  },
  node_id: 'RE_kwDOG8Q6e84NYyec',
  tag_name: 'v1.19.2',
  target_commitish: 'main',
  name: 'v1.19.2',
  draft: false,
  prerelease: false,
  created_at: '2025-06-11T12:59:39Z',
  published_at: '2025-06-11T13:15:32Z',
  assets: [
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262944134',
      id: 262944134,
      node_id: 'RA_kwDOG8Q6e84PrDWG',
      name: 'latest-mac.yml',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'text/yaml',
      state: 'uploaded',
      size: 1172,
      download_count: 1230015,
      created_at: '2025-06-11T13:12:58Z',
      updated_at: '2025-06-11T13:12:59Z',
      browser_download_url: 'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/latest-mac.yml',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943098',
      id: 262943098,
      node_id: 'RA_kwDOG8Q6e84PrDF6',
      name: 'latest.yml',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'text/yaml',
      state: 'uploaded',
      size: 694,
      download_count: 1154760,
      created_at: '2025-06-11T13:08:07Z',
      updated_at: '2025-06-11T13:08:07Z',
      browser_download_url: 'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/latest.yml',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942889',
      id: 262942889,
      node_id: 'RA_kwDOG8Q6e84PrDCp',
      name: 'podman-desktop-1.19.2-arm64.dmg',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 196649765,
      download_count: 18059,
      created_at: '2025-06-11T13:07:24Z',
      updated_at: '2025-06-11T13:07:30Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-arm64.dmg',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942888',
      id: 262942888,
      node_id: 'RA_kwDOG8Q6e84PrDCo',
      name: 'podman-desktop-1.19.2-arm64.dmg.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 206346,
      download_count: 32,
      created_at: '2025-06-11T13:07:24Z',
      updated_at: '2025-06-11T13:07:24Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-arm64.dmg.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942884',
      id: 262942884,
      node_id: 'RA_kwDOG8Q6e84PrDCk',
      name: 'podman-desktop-1.19.2-arm64.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 128626048,
      download_count: 224,
      created_at: '2025-06-11T13:07:24Z',
      updated_at: '2025-06-11T13:07:27Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-arm64.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943464',
      id: 262943464,
      node_id: 'RA_kwDOG8Q6e84PrDLo',
      name: 'podman-desktop-1.19.2-arm64.tar.gz',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/gzip',
      state: 'uploaded',
      size: 135877145,
      download_count: 243,
      created_at: '2025-06-11T13:09:59Z',
      updated_at: '2025-06-11T13:10:02Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-arm64.tar.gz',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943093',
      id: 262943093,
      node_id: 'RA_kwDOG8Q6e84PrDF1',
      name: 'podman-desktop-1.19.2-arm64.zip',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/zip',
      state: 'uploaded',
      size: 191137167,
      download_count: 30427,
      created_at: '2025-06-11T13:08:03Z',
      updated_at: '2025-06-11T13:08:10Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-arm64.zip',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943094',
      id: 262943094,
      node_id: 'RA_kwDOG8Q6e84PrDF2',
      name: 'podman-desktop-1.19.2-arm64.zip.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 201018,
      download_count: 22994,
      created_at: '2025-06-11T13:08:03Z',
      updated_at: '2025-06-11T13:08:03Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-arm64.zip.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943087',
      id: 262943087,
      node_id: 'RA_kwDOG8Q6e84PrDFv',
      name: 'podman-desktop-1.19.2-setup-arm64.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 128807200,
      download_count: 447,
      created_at: '2025-06-11T13:08:02Z',
      updated_at: '2025-06-11T13:08:07Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-setup-arm64.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943088',
      id: 262943088,
      node_id: 'RA_kwDOG8Q6e84PrDFw',
      name: 'podman-desktop-1.19.2-setup-arm64.exe.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 134297,
      download_count: 30,
      created_at: '2025-06-11T13:08:02Z',
      updated_at: '2025-06-11T13:08:02Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-setup-arm64.exe.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943045',
      id: 262943045,
      node_id: 'RA_kwDOG8Q6e84PrDFF',
      name: 'podman-desktop-1.19.2-setup-x64.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 126442616,
      download_count: 23487,
      created_at: '2025-06-11T13:07:50Z',
      updated_at: '2025-06-11T13:07:56Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-setup-x64.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943044',
      id: 262943044,
      node_id: 'RA_kwDOG8Q6e84PrDFE',
      name: 'podman-desktop-1.19.2-setup-x64.exe.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 133676,
      download_count: 29,
      created_at: '2025-06-11T13:07:50Z',
      updated_at: '2025-06-11T13:07:51Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-setup-x64.exe.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942962',
      id: 262942962,
      node_id: 'RA_kwDOG8Q6e84PrDDy',
      name: 'podman-desktop-1.19.2-setup.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 254688112,
      download_count: 32903,
      created_at: '2025-06-11T13:07:38Z',
      updated_at: '2025-06-11T13:07:46Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-setup.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942961',
      id: 262942961,
      node_id: 'RA_kwDOG8Q6e84PrDDx',
      name: 'podman-desktop-1.19.2-setup.exe.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 266114,
      download_count: 12249,
      created_at: '2025-06-11T13:07:38Z',
      updated_at: '2025-06-11T13:07:39Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-setup.exe.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943735',
      id: 262943735,
      node_id: 'RA_kwDOG8Q6e84PrDP3',
      name: 'podman-desktop-1.19.2-universal.dmg',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 314466805,
      download_count: 19333,
      created_at: '2025-06-11T13:11:35Z',
      updated_at: '2025-06-11T13:11:48Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-universal.dmg',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943736',
      id: 262943736,
      node_id: 'RA_kwDOG8Q6e84PrDP4',
      name: 'podman-desktop-1.19.2-universal.dmg.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 330072,
      download_count: 26,
      created_at: '2025-06-11T13:11:35Z',
      updated_at: '2025-06-11T13:11:35Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-universal.dmg.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262944093',
      id: 262944093,
      node_id: 'RA_kwDOG8Q6e84PrDVd',
      name: 'podman-desktop-1.19.2-universal.zip',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/zip',
      state: 'uploaded',
      size: 306196893,
      download_count: 42,
      created_at: '2025-06-11T13:12:47Z',
      updated_at: '2025-06-11T13:12:58Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-universal.zip',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262944092',
      id: 262944092,
      node_id: 'RA_kwDOG8Q6e84PrDVc',
      name: 'podman-desktop-1.19.2-universal.zip.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 321500,
      download_count: 25,
      created_at: '2025-06-11T13:12:47Z',
      updated_at: '2025-06-11T13:12:47Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-universal.zip.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942279',
      id: 262942279,
      node_id: 'RA_kwDOG8Q6e84PrC5H',
      name: 'podman-desktop-1.19.2-x64.dmg',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 204735016,
      download_count: 4999,
      created_at: '2025-06-11T13:04:27Z',
      updated_at: '2025-06-11T13:04:35Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-x64.dmg',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942278',
      id: 262942278,
      node_id: 'RA_kwDOG8Q6e84PrC5G',
      name: 'podman-desktop-1.19.2-x64.dmg.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 211711,
      download_count: 25,
      created_at: '2025-06-11T13:04:27Z',
      updated_at: '2025-06-11T13:04:27Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-x64.dmg.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942872',
      id: 262942872,
      node_id: 'RA_kwDOG8Q6e84PrDCY',
      name: 'podman-desktop-1.19.2-x64.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 126261160,
      download_count: 1121,
      created_at: '2025-06-11T13:07:18Z',
      updated_at: '2025-06-11T13:07:24Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-x64.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942421',
      id: 262942421,
      node_id: 'RA_kwDOG8Q6e84PrC7V',
      name: 'podman-desktop-1.19.2-x64.zip',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/zip',
      state: 'uploaded',
      size: 199256516,
      download_count: 3004,
      created_at: '2025-06-11T13:05:05Z',
      updated_at: '2025-06-11T13:05:16Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-x64.zip',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942420',
      id: 262942420,
      node_id: 'RA_kwDOG8Q6e84PrC7U',
      name: 'podman-desktop-1.19.2-x64.zip.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 210016,
      download_count: 2122,
      created_at: '2025-06-11T13:05:05Z',
      updated_at: '2025-06-11T13:05:05Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-x64.zip.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942860',
      id: 262942860,
      node_id: 'RA_kwDOG8Q6e84PrDCM',
      name: 'podman-desktop-1.19.2.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 254506912,
      download_count: 1216,
      created_at: '2025-06-11T13:07:14Z',
      updated_at: '2025-06-11T13:07:25Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943080',
      id: 262943080,
      node_id: 'RA_kwDOG8Q6e84PrDFo',
      name: 'podman-desktop-1.19.2.flatpak',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 98100240,
      download_count: 3542,
      created_at: '2025-06-11T13:08:00Z',
      updated_at: '2025-06-11T13:08:03Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2.flatpak',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943276',
      id: 262943276,
      node_id: 'RA_kwDOG8Q6e84PrDIs',
      name: 'podman-desktop-1.19.2.tar.gz',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/gzip',
      state: 'uploaded',
      size: 135728127,
      download_count: 1612,
      created_at: '2025-06-11T13:09:03Z',
      updated_at: '2025-06-11T13:09:07Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2.tar.gz',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262944041',
      id: 262944041,
      node_id: 'RA_kwDOG8Q6e84PrDUp',
      name: 'podman-desktop-airgap-1.19.2-arm64.dmg',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 1152804820,
      download_count: 229,
      created_at: '2025-06-11T13:12:38Z',
      updated_at: '2025-06-11T13:13:25Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-arm64.dmg',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262944042',
      id: 262944042,
      node_id: 'RA_kwDOG8Q6e84PrDUq',
      name: 'podman-desktop-airgap-1.19.2-arm64.dmg.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 1196697,
      download_count: 23,
      created_at: '2025-06-11T13:12:38Z',
      updated_at: '2025-06-11T13:12:38Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-arm64.dmg.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943150',
      id: 262943150,
      node_id: 'RA_kwDOG8Q6e84PrDGu',
      name: 'podman-desktop-airgap-1.19.2-arm64.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 321874272,
      download_count: 27,
      created_at: '2025-06-11T13:08:21Z',
      updated_at: '2025-06-11T13:08:33Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-arm64.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262944325',
      id: 262944325,
      node_id: 'RA_kwDOG8Q6e84PrDZF',
      name: 'podman-desktop-airgap-1.19.2-arm64.zip',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/zip',
      state: 'uploaded',
      size: 1146076438,
      download_count: 28,
      created_at: '2025-06-11T13:14:06Z',
      updated_at: '2025-06-11T13:14:42Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-arm64.zip',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262944326',
      id: 262944326,
      node_id: 'RA_kwDOG8Q6e84PrDZG',
      name: 'podman-desktop-airgap-1.19.2-arm64.zip.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 1190309,
      download_count: 26,
      created_at: '2025-06-11T13:14:06Z',
      updated_at: '2025-06-11T13:14:06Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-arm64.zip.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943320',
      id: 262943320,
      node_id: 'RA_kwDOG8Q6e84PrDJY',
      name: 'podman-desktop-airgap-1.19.2-setup-arm64.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 322055424,
      download_count: 64,
      created_at: '2025-06-11T13:09:13Z',
      updated_at: '2025-06-11T13:09:26Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-setup-arm64.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943321',
      id: 262943321,
      node_id: 'RA_kwDOG8Q6e84PrDJZ',
      name: 'podman-desktop-airgap-1.19.2-setup-arm64.exe.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 335258,
      download_count: 25,
      created_at: '2025-06-11T13:09:13Z',
      updated_at: '2025-06-11T13:09:13Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-setup-arm64.exe.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943266',
      id: 262943266,
      node_id: 'RA_kwDOG8Q6e84PrDIi',
      name: 'podman-desktop-airgap-1.19.2-setup-x64.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 325567744,
      download_count: 925,
      created_at: '2025-06-11T13:08:57Z',
      updated_at: '2025-06-11T13:09:06Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-setup-x64.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943267',
      id: 262943267,
      node_id: 'RA_kwDOG8Q6e84PrDIj',
      name: 'podman-desktop-airgap-1.19.2-setup-x64.exe.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 341774,
      download_count: 30,
      created_at: '2025-06-11T13:08:57Z',
      updated_at: '2025-06-11T13:08:58Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-setup-x64.exe.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943212',
      id: 262943212,
      node_id: 'RA_kwDOG8Q6e84PrDHs',
      name: 'podman-desktop-airgap-1.19.2-setup.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 647061464,
      download_count: 31,
      created_at: '2025-06-11T13:08:42Z',
      updated_at: '2025-06-11T13:09:03Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-setup.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943213',
      id: 262943213,
      node_id: 'RA_kwDOG8Q6e84PrDHt',
      name: 'podman-desktop-airgap-1.19.2-setup.exe.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 675255,
      download_count: 25,
      created_at: '2025-06-11T13:08:43Z',
      updated_at: '2025-06-11T13:08:43Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-setup.exe.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943086',
      id: 262943086,
      node_id: 'RA_kwDOG8Q6e84PrDFu',
      name: 'podman-desktop-airgap-1.19.2-x64.dmg',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 1218526439,
      download_count: 78,
      created_at: '2025-06-11T13:08:02Z',
      updated_at: '2025-06-11T13:08:55Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-x64.dmg',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943085',
      id: 262943085,
      node_id: 'RA_kwDOG8Q6e84PrDFt',
      name: 'podman-desktop-airgap-1.19.2-x64.dmg.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 1263127,
      download_count: 23,
      created_at: '2025-06-11T13:08:02Z',
      updated_at: '2025-06-11T13:08:02Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-x64.dmg.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943136',
      id: 262943136,
      node_id: 'RA_kwDOG8Q6e84PrDGg',
      name: 'podman-desktop-airgap-1.19.2-x64.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 325386288,
      download_count: 81,
      created_at: '2025-06-11T13:08:14Z',
      updated_at: '2025-06-11T13:08:26Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-x64.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943339',
      id: 262943339,
      node_id: 'RA_kwDOG8Q6e84PrDJr',
      name: 'podman-desktop-airgap-1.19.2-x64.zip',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/zip',
      state: 'uploaded',
      size: 1211626956,
      download_count: 43,
      created_at: '2025-06-11T13:09:23Z',
      updated_at: '2025-06-11T13:10:04Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-x64.zip',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943341',
      id: 262943341,
      node_id: 'RA_kwDOG8Q6e84PrDJt',
      name: 'podman-desktop-airgap-1.19.2-x64.zip.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 1264339,
      download_count: 24,
      created_at: '2025-06-11T13:09:23Z',
      updated_at: '2025-06-11T13:09:25Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-x64.zip.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943100',
      id: 262943100,
      node_id: 'RA_kwDOG8Q6e84PrDF8',
      name: 'podman-desktop-airgap-1.19.2.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 646880272,
      download_count: 36,
      created_at: '2025-06-11T13:08:08Z',
      updated_at: '2025-06-11T13:08:31Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262945118',
      id: 262945118,
      node_id: 'RA_kwDOG8Q6e84PrDle',
      name: 'store-cache-pnpm-amd64.tgz',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'binary/octet-stream',
      state: 'uploaded',
      size: 421445393,
      download_count: 18,
      created_at: '2025-06-11T13:17:25Z',
      updated_at: '2025-06-11T13:17:37Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/store-cache-pnpm-amd64.tgz',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262945792',
      id: 262945792,
      node_id: 'RA_kwDOG8Q6e84PrDwA',
      name: 'store-cache-pnpm-arm64.tgz',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'binary/octet-stream',
      state: 'uploaded',
      size: 417784341,
      download_count: 15,
      created_at: '2025-06-11T13:21:16Z',
      updated_at: '2025-06-11T13:21:27Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/store-cache-pnpm-arm64.tgz',
    },
  ],
  tarball_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/tarball/v1.19.2',
  zipball_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/zipball/v1.19.2',
  body: `## What's Changed\r\n* chore: update podman to v5.5.1 (backport #12762) by @mergify in https://github.com/podman-desktop/podman-desktop/pull/12804\r\n\r\n\r\n**Full Changelog**: https://github.com/podman-desktop/podman-desktop/compare/v1.19.1...v1.19.2`,
  reactions: {
    url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/224602012/reactions',
    total_count: 6,
    '+1': 3,
    '-1': 0,
    laugh: 0,
    hooray: 0,
    confused: 0,
    heart: 2,
    rocket: 1,
    eyes: 0,
  },
  mentions_count: 1,
};
